// Generated by packetc v0.2.3 at Thu, 11 Feb 2021 18:03:32 +0000
import { Reader, Writer } from "packet";
export const enum Action {
    MoveLeft = 1 << 0,
    MoveRight = 1 << 1,
    MoveUp = 1 << 2,
    MoveDown = 1 << 3,
    Jump = 1 << 4,
    LetGo = 1 << 5,
}
function Action_try_from(value: number): Action {
    if (Action.MoveLeft <= value && value <= Action.LetGo) { return value; }
    else throw new Error(`'${value}' is not a valid 'Action' value`);
}
export interface Input {
    action: Action,
}
export function read(reader: Reader, output: Input) {
    output.action = Action_try_from(reader.read_uint8());
}
export function write(writer: Writer, input: Input) {
    writer.write_uint8(input.action as number);
}
