// Generated by packetc v0.3.4 at Sat, 27 Feb 2021 15:47:51 +0000
import { Reader, Writer } from "packet";
export namespace Delete {
}
export class Delete {
    constructor(
        public id: number,
    ) {}
    static read(data: ArrayBuffer): Delete | null {
        let reader = new Reader(data);
        let output = Object.create(Delete);
        output.id = reader.read_uint32();
        if (reader.failed) return null;
        return output;
    }
    write(buffer?: ArrayBuffer): ArrayBuffer {
        let writer = buffer ? new Writer(buffer) : new Writer();
        writer.write_uint32(this.id);
        return writer.finish();
    }
}
