// Generated by packetc v0.3.4 at Mon, 01 Mar 2021 17:54:33 +0000
import { Reader, Writer } from "packet";
export namespace Position {
}
export class Position {
    constructor(
        public cstate: number,
        public x: number,
        public y: number,
    ) {}
    static read(data: ArrayBuffer): Position | null {
        let reader = new Reader(data);
        let output = Object.create(Position);
        output.cstate = reader.read_uint8();
        output.x = reader.read_float();
        output.y = reader.read_float();
        if (reader.failed) return null;
        return output;
    }
    write(buffer?: ArrayBuffer): ArrayBuffer {
        let writer = buffer ? new Writer(buffer) : new Writer();
        writer.write_uint8(this.cstate);
        writer.write_float(this.x);
        writer.write_float(this.y);
        return writer.finish();
    }
}
