
name: Client CI

on:
  push:
    paths:
      - .github/workflows/client-ci.yml
      - client/public
      - client/src
      - client/jest.config.js
      - client/package.json
      - client/package-lock.json
      - client/snowpack.config.js
      - client/tsconfig.json
  pull_request:
    paths:
      - .github/workflows/client-ci.yml
      - client/public
      - client/src
      - client/jest.config.js
      - client/package.json
      - client/package-lock.json
      - client/snowpack.config.js
      - client/tsconfig.json

defaults:
  run:
    working-directory: client

jobs:
  # runs typescript build + test
  ts:
    name: TypeScript 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 15
    steps:
      # get code + setup node toolchain
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Get Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      # install, build, test
      - run: npm install
      - run: npm run build
      - run: npm run test