
name: Server CI

on:
  push:
    paths:
      - .github/workflows/server-ci.yml
      - server/Cargo.toml
      - server/Cargo.lock
      - server/src/**
  pull_request:
    paths:
      - .github/workflows/server-ci.yml
      - server/Cargo.toml
      - server/Cargo.lock
      - server/src/**

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run type checking
        run: cargo check --manifest-path=server/Cargo.toml

      - name: Run tests
        run: cargo test --manifest-path=server/Cargo.toml

      # The following two steps are optional, because sometimes 
      # the nightly toolchain doesn't have all components ready, 
      # in which case we don't want CI to fail.
      
      - name: Get rustfmt
        id: getfmt
        run: rustup component add rustfmt
        continue-on-error: true
      - name: Check formatting
        if: steps.getfmt.outcome == 'success'
        run: cargo fmt --manifest-path=server/Cargo.toml --all -- --check

      - name: Get clippy
        id: getclippy
        run: rustup component add clippy
        continue-on-error: true
      - name: Lint
        if: steps.getclippy.outcome == 'success'
        run: cargo clippy --manifest-path=server/Cargo.toml -- -D warnings